[package]
name = "monsters"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
genetics =  {git="https://github.com/ChousX/genetics.git"}
bevy = "0.7"
noise = "*"